### PR TITLE
#1072 Working preferences questions

### LINKED ISSUE #1072: Working preferences questions
See Admin: [Configure working preferences questions](/jac-uk/admin/issues/2154)

There are a number of configuration changes outlined in [Configure working preferences questions](/jac-uk/admin/issues/2154).

Here we need to ensure these changes are correctly rolled out to the application form.

In particular:

## Improvements to existing functionality

- [x] Working preferences questions should be mandatory (if configured)
- [x] Ranking. Should not be able to skip numbers - e.g. choosing two answers from five means user can choose 1st and 2nd choice, not 1st and 5th
- [x] There can now be multiple location questions (currently there is only one)
- [x] There can now be multiple jurisdiction questions (currently there is only one)

## Use Jurisdictions from Vacancy Information

- [x] Ensure that we display answers from Vacancy Information > Jurisdictions if the question is configured

## Allow linked questions

- [x] Ensure linked questions are only asked if the corresponding linked answer has been selected
- [ ] Improve the navigation / ensure we ask linked questions from another preference type (either combine the preference questions into one page OR ensure linked questions from another preference are asked on both preference pages) 

## Allow grouping of answers

- [x] Display answer groups and nested answers

## Review

- [x] Update the Review page to correctly display the candidate's selections

https://github.com/jac-uk/apply/assets/8524401/3d87a3cd-c129-4f51-8a8c-279cb918105e

---

See the following [visuals](https://www.figma.com/file/aqILfbMFEy51XDaFZpid8i/Ranked-answers-with-linked-questions?type=design&mode=design)

### LINKED ISSUE #1162: PSDQ. Working preferences. Update to use the latest location and jurisdiction preferences
Working Preferences has been updated and now needs to be rolled out to the Pre Selection Day Questionnaire. 

This includes:
 - [x] Task list. Location preferences. Should display correctly and show DONE tag when the form has been completed
 - [x] Task list. Jurisdiction preferences. Should display correctly and show DONE tag when the form has been completed
 - [x] Location preferences. Form should work without errors and correctly mark the part as DONE
 - [x] Jurisdiction preferences. Form should work without errors and correctly mark the part as DONE
 - [x] Review. Location and jurisdiction preferences should be displayed correctly and the data should be editable (until the questionnaire has been submitted)

### PR DESCRIPTION
**Pull request by warrensearle**
## What's included?

Improvements to the working preferences questions, as follows:

- [x] Working preferences questions should be mandatory (if configured)
- [x] Ranking. Should not be able to skip numbers - e.g. choosing two answers from five means user can choose 1st and 2nd choice, not 1st and 5th
- [x] There can now be multiple location questions.
- [x] There can now be multiple jurisdiction questions.
- [x] SETs can configure how many answers candidates should select (for multiple & ranked choices)
- [x] Questions can be linked together so answering one question, with a particular answer, means a follow-on question is asked
- [x] To aid navigation answers can now be grouped together
- [x] Review page should display answers

Closes #1072
Closes #1162 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

This should be tested alongside https://github.com/jac-uk/admin/pull/2207.

We decided to continue to support current functionality for existing exercises and have new exercises benefit from the new functionality.

There are therefore two areas to test:

**1. There should not be any breaking changes for existing exercises**

Pick an existing exercise configured with original working preferences functionality (use the existing exercise chosen/created in part 1 of testing [this PR](https://github.com/jac-uk/admin/pull/2207))

Create an application and in particular check that working preferences questions can be answered and edited.
Before submitting your application check that preference answers are correctly displayed on the Review screen. 

Please highlight any breaking changes.

**2. New exercises should benefit from the new functionality and the new functionality satisfies user requirements**

Use the new exercise created in part 2 of testing [this PR](https://github.com/jac-uk/admin/pull/2207)

Create a new application and in particular complete all of the Working preferences questions and review your answers.

Please highlight any issues with, or suggestions for, the new functionality.

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by nickaddy — APPROVED** [review]
@warrensearle Looking good! Let's put to UT this week and see what the users have to say :-)

**Review by HalcyonJAC — CHANGES_REQUESTED** [review]
The functionality works for me. @Franceswog spotted that there is a validation issue on "Date of birth" on the "Create an account" page but it works well on develop. It might be related to the changes of `FormField.vue`. Could you check it, please?

Screenshot 2024-02-02 at 13 48 43

**Comment by warrensearle** [comment]
@nickaddy please can you re-test? Omar has implemented a fix for the inconsistency raised by Matt.

**Review by NormaJAC — COMMENTED** [review]
Already applied, I could still make the required choices.

**Comment by nickaddy** [comment]
@warrensearle So the designed solution is to trigger an alert to users to manually update their rankings?

**Comment by nickaddy** [comment]
@warrensearle In the grouped answers section, if you tick 1 in group 1, should that automatically tick 2 in group 2? I'm not sure this is right?

**Comment by Franceswog** [comment]
When I click on group 1, group 2 select its self automatically, should this be the case? Also Should a user be able to save this new changes?

**Comment by Franceswog** [comment]
@warrensearle during UT, a few people had a constant issue while logging into apply to carry out the test. It turned out there was a formatting / validation issue which caused a bug. They could not get pass the sign in page where  Date of birth is needed to create a login. It came up with an error message ' DOB has been entered incorrectly'. This is not to say the exercise failed UT because most of us tested it successfully but the format needs to be looked into again.

**Comment by drieJAC** [comment]
@Franceswog reported that users are having problems signing up. The date of birth field shows an error for missing a required field when the value is entered.
After investigation it appears that this is associated with the changes to the FormField.vue component.
I'm currently investigating a fix.

**Review by NormaJAC — APPROVED** [review]

**Review by drieJAC — APPROVED** [review]

**Comment by warrensearle** [comment]
UT feedback:

 - [ ] Doesn't sound like a new exercise was configured for testing. Make sure a new exercise is set up ready for testing this week

**Comment by warrensearle** [comment]
I have refreshed the same test exercise so it is now ready for testing

**Review by HalcyonJAC — APPROVED** [review]

**Comment by warrensearle** [comment]
Hi @nickaddy 

I have fixed point 3 above so that linked questions should now appear as expected.

For point 1 the question was configured as 'Required' and also to allow 'any' number of answers to be chosen. To allow no answers the question needs to be configured as optional. Perhaps there is an improvement to be made in admin otherwise this is just a data issue with the misleading title given to the question.

@drieJAC please can you address point 2. I agree with Nick that if you have for example selected ranks of 1,1,2,2 then the dropdown for ranks should only contain 1, 2 and 3. Currently the dropdown contains 1, 2, 3, 4, and 5 which enables the user to have gaps in their selected ranks. I know you had strong (and logical) opinions on this so if you have any concerns please DM Nick or outline in a reply here. Thank you!

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Comment by warrensearle** [comment]
I propose closing this ticket and moving any future changes or bugs to new tickets.

Note that I have re-opened the following two tickets as this functionality needs to be updated with changes/simplifications made in this pull request:

https://github.com/jac-uk/admin/issues/2318

https://github.com/jac-uk/admin/issues/2319

I have also created a new bug ticket here:

https://github.com/jac-uk/apply/issues/1178

**Comment by warrensearle** [comment]
@nickaddy please can you approve this PR, particularly if you agree with the above suggestion

**Review by nickaddy — APPROVED** [review]

**Review by HalcyonJAC — APPROVED** [review]

**Pull request merged**
