### PR TITLE
hide archived exercises

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
RE: archiving exercises on the admin interface, this hides any archived exercises from the main view, while still allowing those who have applied to see their data.
Likely needs more design thought than this and improvements, and assurance of where and where not, and how and how not archived exercises and applications are displayed to candidates. 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Assure that an archived exercise doesn't display in the main list, but that the advert page and any entered data for that application can be accessed by a candidate who has made an application.

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by andrew-isaac** [comment]
Can I get a preview URL please :)

**Review by HalcyonJAC — APPROVED** [review]
LGTM 👍

**Review by warrensearle — APPROVED** [review]

**Review by andrew-isaac — CHANGES_REQUESTED** [review]
Was the bugs in UT fixed?

- [ ] - When unarchived an exercise became stuck in a loop and wouldn't move back to live
- [ ] - Publishing of the exercise should be removed
- [ ] - Processing of applications should be removed
- [ ] - Any function where a user can send out information should be disabled
- [ ] - When pressing next on the live list the page was not moving to the next page

**Review by andrew-isaac — APPROVED** [review]
Great work Tom - Lets send this back for User Testing on 14/9/22

**Pull request merged**
