### PR TITLE
Bugfix/1103 User directed to Create an Account page at Log-in

### LINKED ISSUE #1103: User directed to Create an Account page at Log-in
Background
I have observed this previously, but thought it had been fixed in the Vue upgrade.

Description
When a user logs in, they should be directed to the homepage with links to Current vacancies, their applications, etc. However, on some occasions, the user is taken to the 'Create an Account' page on login - see screenshot below:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26ea075afed443db913ba779f34a87275acffe78/image.png)

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #1103 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

Preview URL: https://jac-apply-develop--pr1132-bugfix-1103-user-dir-i9zcqroo.web.app/

Make sure you sign out first.

#### Create an account
1. Go to "Create an account" page from "Sign in" page.
2. Click "Sign In" button at the top right.
3. Check if the page redirects to "Vacancies" page after sign-in.

https://github.com/jac-uk/apply/assets/79906532/9a28f991-4e49-4478-ac4e-2dac3f0f986a

#### Reset your password
1. Go to "Reset your password" page from "Sign in" page.
2. Click "Sign In" button at the top right.
3. Check if the page redirects to "Vacancies" page after sign-in.

https://github.com/jac-uk/apply/assets/79906532/142304b8-ab8e-4d66-a0d5-6b67fd51b65b

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by warrensearle — APPROVED** [review]
👍 looks good to me. Thanks for also including the reset password page in this fix

**Review by nickaddy — CHANGES_REQUESTED** [review]
I am unable to log in despite my UN/PW details being correct

**Comment by HalcyonJAC** [comment]
> I am unable to log in despite my UN/PW details being correct

Hi @nickaddy, which email address did you log in with?

**Comment by nickaddy** [comment]
@HalcyonJAC nick.addy@judicialappointments.digital

**Comment by nickaddy** [comment]
@HalcyonJAC 
image

**Review by nickaddy — APPROVED** [review]
Works with the dummy email address

**Review by Franceswog — COMMENTED** [review]
I was able to view vacancies from the  sign in page and it also directed me to vacancies page after I signed in . In the sign in page,  'forgotten password'  is called 'reset password' , should this be the case? However, when you click on reset password it takes you to the page 'forgotten password' to reset your password. 
image

**Comment by warrensearle** [comment]
> In the sign in page, 'forgotten password' is called 'reset password' , should this be the case? However, when you click on reset password it takes you to the page 'forgotten password' to reset your password. 

Great spot @Franceswog 💯

**Comment by HalcyonJAC** [comment]
@Franceswog Thank you. That's a good spot. I guess there are two options:
1. In Sign-in page, change the wording from "Reset your password" to "Forgotten password".
2. In Forgotten password page, change the title from "Forgotten password" to "Reset your password".

@nickaddy Do you have any thoughts on it?

**Comment by Franceswog** [comment]
@HalcyonJAC , On a sign in page, I believe a user would  want to see 'forgotten password ' in the event their login details fail, which was what I was looking for following your instruction during the test. .  

My preference will be option 1-

In Sign-in page, change the wording from "Reset your password" to "Forgotten password".  This would take them to the page to the existing page 'Forgotten password' where they can 'Reset password'

**Comment by nickaddy** [comment]
@HalcyonJAC @Franceswog Agreed - on the sign in page, pls remove all the text currently under the continue button and replace with **Forgot password?**

On the Forgotten password page: 
- Change the title to **Reset your password**
- Change We'll to **We will**
- Change the text on the Send the link button to **Reset password**

**Comment by HalcyonJAC** [comment]
@nickaddy @Franceswog I have updated the wording. Could you re-test it, please?

**Comment by nickaddy** [comment]
@HalcyonJAC Can you also action this bit pls:

 On the sign in page, pls remove all the text currently under the continue button and replace with **Forgot password?**

**Review by nickaddy — APPROVED** [review]
Neat and tidy, thx Ryan :-)

**Review by Franceswog — APPROVED** [review]
Looking good , happy Days ..

**Review by NormaJAC — COMMENTED** [review]
I was able to sign in to both the Reset your password and Create an account pages, I was redirected to the Vacancies page after sign-in on both occasions.

**Pull request merged**
