### PR TITLE
show/hide-RA-details

### PR DESCRIPTION
**Pull request by tomlovesgithub**
**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---

## What's included?
Details for reasonable adjustments are showing regardless of weather the RA field is true or false.
This was highlighted in tests for 283.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- On an application review page, go to 'Change' under personal details; 
- Ensure there is text in the 'Reasonable Adjustments Details' section.
- Select 'No' for 'Reasonable Adjustment'
- Save and Continue
- **Any details entered should NOT show**
- Go to 'Change' under personal details; 
- Ensure there is text in the 'Reasonable Adjustments Details' section.
- Select 'Yes' for 'Reasonable Adjustment'
- Save and Continue
- **Any details entered SHOULD show**

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by mbrookeswebdev** [comment]
@tomlovesgithub the text still shows on Admin when clicked 'No' -

Sc1

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
Please see the comment from earlier

**Comment by lloback** [comment]
The code on this PR is working (only changes to apply)
If "Yes" show the information
image
If "No" doesn't show the reason for reasonable adjustment
image

**Review by lloback — APPROVED** [review]
✔︎
@mbrookeswebdev please review only on apply, as the code is not related to admin. This code is working correctly on apply.  You can go directly to the review page by adding `/review` at the end of the URL (as you know) Cheers.

**Review by mbrookeswebdev — APPROVED** [review]

**Comment by mbrookeswebdev** [comment]
@tomlovesgithub @joy-ade Perhaps a ticket should be created to fix the issue on Admin side?

**Comment by joy-ade** [comment]
@mbrookeswebdev there is already ticket 1329 on the Admin side to fix the issues.

**Review by joy-ade — APPROVED** [review]
Approved by product team  and UTG

**Comment by KateMJAC** [comment]
On advice from Lee this can now be merged.

**Pull request merged**
