### PR TITLE
1134/upgrade apply firebase

### LINKED ISSUE #1134: Upgrade Apply Platform to use latest Firebase library
Following the upgrade of Admin repo, we need to upgrade the other repos to the latest version.

Useful links

https://firebase.google.com/docs/web/modular-upgrade

[ ] [jac-kit] Upgrade Firebase SDK to latest stable version
[ ] [admin] Upgrade Firebase SDK to latest stable version
[ ] [jac-kit] Update all the import statements from firebase to firebase/compat
[ ] [admin] Update all the import statements from firebase to firebase/compat
[ ] Refactoring Authentication functions to modular APIs
[ ] Refactoring Firestore functions to modular APIs
[ ] Refatoring firestoreAction
[ ] Update Firestore Action in store/*.js files
[ ] Upgrade VuexFire to VueFire

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
closes #1134

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?`
Go to the preview link: 
All of the functionality of the admin site:
- Sign-in/Sign-out
- All tables
- All functionalities for creating/updating/deleting data
- All functionalities for upload/download/preview files

## Risk - how likely is this to impact other areas?
🔴 High risk - this includes changes to all code

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by drieJAC — APPROVED** [review]

**Comment by nickaddy** [comment]
@tomlovesgithub Tested t
his morning and have received a multitude of errors, see below.

1.	Don’t log in
Navigate to ‘Closed for Applications’
Choose an exercise
Receive the Loading spinner

2.	Don’t log in
Navigate to ‘Future Applications’
Choose an exercise
Receive the Loading spinner

3.	Log in
Navigate to any of ‘Closed for Applications’, ‘Future Applications’ or ‘Open for Applications’, click on an exercise to apply for and receive this message:
 

4.	Click on ‘Your Profile’ – no content appears in main window
5.	Click on ‘Applications’, select any application and receive this message:

**Comment by HalcyonJAC** [comment]
@tomlovesgithub I tested it and had some issues:

- "Reset password" is not working.
- "Create an account" is not working.
- Apply for a vacancy
  - "Save and continue" is not working.

**Comment by nickaddy** [comment]
@tomlovesgithub Following issues identified at UT on 27/03:

- [ ] When trying to change password, error message received `Yr.currentUser.updatePassword is not a function`
- [ ] When clicking on `View draft application` taken to a blank page Home>Apply>Review but the draft application is not loading 
- [ ] When trying to upload dummy Statement of Suitability for Vacancy, it would not upload so could not continue with application. Same when trying to upload dummy CV.
 
Pls address and let's retest next week.

**Comment by tomlovesgithub** [comment]
> * [ ]  When clicking on `View draft application` taken to a blank page Home>Apply>Review but the draft application is not loading

@nickaddy unable to reproduce this myself, could you provide me with the details of the exercise you were experiencing this bug with?

https://github.com/jac-uk/apply/assets/44227249/0f74b4b7-b6f2-4cac-b20b-955bfdcfe45d

**Comment by KoWeiJAC** [comment]
@tomlovesgithub 
Not sure if these issues are because of outdated data or latest changes not sync to the firebase upgrade branch:
I'm using `application-0008@jac-dummy-email.jac` account for testing.

* Go to `Current applications` , then find the application having`Pre Selection Day Questionnaire` and click the  `Pre Selection Day Questionnaire` button.
It doesn't show the questionnaire form and having an error in the console.
Screenshot 2024-04-15 at 11 22 08

* Can't submit recent applications, I was testing with following applications: 
- https://jac-apply-develop--pr1151-1134-upgrade-apply-f-q5ose0a7.web.app/apply/lfMM5Ho5qDD7Uuzhi0Zf/review
- https://jac-apply-develop--pr1151-1134-upgrade-apply-f-q5ose0a7.web.app/apply/IbeEVi4Vtrpv9eVFzhZq/review
Screenshot 2024-04-15 at 11 23 36

**Comment by KoWeiJAC** [comment]
@tomlovesgithub 
Found some issues not sure if they're related to firebase upgrade.
I'm using application-0008@jac-dummy-email.jac account for testing.
* Send EventLog Failed, go to this page and click save, the console will show `POST https://europe-west2-digital-platform-develop.cloudfunctions.net/logEvent 500 (Internal Server Error)`
https://jac-apply-develop--pr1151-1134-upgrade-apply-f-q5ose0a7.web.app/apply/isMrU9nmsJbPaUvnp8Mf/cv

https://github.com/jac-uk/apply/assets/156695133/bc8e662a-de90-41e2-9708-995175a3e069



* Try to save `Self assessment competencies`, it will have an error
 https://jac-apply-develop--pr1151-1134-upgrade-apply-f-q5ose0a7.web.app/apply/isMrU9nmsJbPaUvnp8Mf/self-assessment-competencies
 
Screenshot 2024-04-15 at 12 58 03

**Review by HalcyonJAC — APPROVED** [review]

**Pull request merged**
