### PR TITLE
#1355 Updated Review page to correctly show answers related to Welsh posts

### PR DESCRIPTION
**Pull request by mbrookeswebdev**
**Author checklist**

- ✅  Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- ✅  Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---

## What's included?
Made small changes to Review component to correctly show answers related to Welsh posts/requirements.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
As a candidate apply for a vacancy with Welsh posts and Welsh requirements.
Ensure that candidate answers on the application Review page->Welsh posts section correctly reflect provided information.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Application Review page:

Sc1

---
PREVIEW:DEVELOP

### CODE REVIEW

**Review by HalcyonJAC — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]
Looks good to me 👍

**Review by tomlovesgithub — APPROVED** [review]

**Comment by KateMJAC** [comment]
Sent to UTG 5/7/21. Feedback to follow.

**Review by KateMJAC — COMMENTED** [review]
Sent to UTG 5/7/21. Feedback to follow.

**Review by joy-ade — APPROVED** [review]
approved by product team and UTG

**Pull request merged**
