### PR TITLE
Bugfix/Issue 190 Self assessment extraction

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?

Mentions [issue 190](https://github.com/jac-uk/ticketing-system/issues/190)

- Show the question text in the review of the self-assessment.
  
  image

  image

- Show line breaks on the extracted self-assessment content.

## Who should test?
✅ Product owner
✅ Developers

## How to test?
- Example vacancy: https://jac-apply-develop--pr1138-bugfix-issue-190-sel-a9ov50fs.web.app/vacancy/nrNvxQxa38XkFrE0ps5j/

- Example self-assessment file:
[self-assessment-example.docx](https://github.com/jac-uk/apply/files/14268636/self-assessment-example.docx)

Steps:
1. Apply for the vacancy.
2. Go to "Self assessment with competencies" and upload the self-assessment file. 
3. Click "Save and continue" and check if the questions and answers are extracted correctly with line breaks.
4. Go to the Review page and check if the self-assessment content shows correctly with line breaks.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://github.com/jac-uk/apply/assets/79906532/53540a4d-4468-4025-8613-0f0c2bb47683

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by nickaddy — CHANGES_REQUESTED** [review]
@HalcyonJAC After I have uploaded the document, I am unable to click `Save and continue`

image

**Review by tomlovesgithub — APPROVED** [review]

**Review by drieJAC — APPROVED** [review]

**Review by NormaJAC — COMMENTED** [review]
I uploaded the self assessment example document. It showed the line breaks on the extracted content.

**Comment by HalcyonJAC** [comment]
@nickaddy It's because your application has been submitted. I have marked it as draft. Could you test it again, please?

**Comment by nickaddy** [comment]
@HalcyonJAC This is not working, I'm afraid. What it does now is to cut the off content from the first box after a carriage return. That then goes in to the second box and so on and it all gets out of sync, then anything left over gets chucked into the final box.

Additionally, i don't know what word limits were set for these questions, but I do not see anywhere the Word count and whether it has been exceeded. 

Would a possible solution be to strip out carriage returns from the content in each box in Word and then it may be correctly split over the fields on the platform?

**Comment by HalcyonJAC** [comment]
@nickaddy The improvement of the file extraction has been made in the cloud function in this [PR](https://github.com/jac-uk/digital-platform/pull/1015). The changes in this PR are to preserve the line breaks if there is more than one paragraph in a box. Hope it makes sense.

**Comment by nickaddy** [comment]
@HalcyonJAC I'm wondering whether this is in fact the right approach to the issue - it is not resolving the overall issue of content being played back on the platform as input to the fields on the word document. Would a better approach not be to strip out the carriage returns from the content before parsing into the relevant fields on the platform?

**Review by Franceswog — APPROVED** [review]

**Review by nickaddy — APPROVED** [review]
Great work, Ryan - content is extracted correctly into 5 fields as per the number of questions in the uploaded document.

**Review by drieJAC — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC I am unable to click `Save and continue`
image

**Comment by HalcyonJAC** [comment]
@nickaddy It was because your application had been submitted. I have moved your application to Draft and you should be able to click `Save and continue`.

**Pull request merged**
