### PR TITLE
Feature/1066 Capture commissioner conflicts

### LINKED ISSUE #1066: Capture Commissioner Conflicts
**User Story** 
As an applicant, I would like to specify any commissioner conflicts so that this can be taken into account during my application.

**[Background]**
Currently, commissioner conflicts are captured on Google Forms, but the objective is to embed this functionality on the platform. Additionally, Judicial Office are keen that this information is captured in the early stages of application. 
Currently only Commissioner email addresses are captured in the database; we need to add their names too.
We would like to provide candidates with the opportunity to declare any pre-existing relationships they have with the JAC Commissioners so that this information can be taken into account when assessing their applications.

**Feature** 
This is a new section to be added under Additional Information.
We should present to the candidates a list of the commissioners names from the database with the option to select yes/no radio buttons for each one. 
By default all radio buttons should be deselected.
When 'yes' is selected, a free text box should appear under that commissioner, prompting the applicant to enter details of their relationship.

[Miro board here](https://miro.com/app/board/uXjVMhy_k0o=/?share_link_id=19922587091)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14e8afef69c37f3f853a30e276950f6a892d8764/image.png)

**MOSCOW**
Use this technique to prioritise all requirements .
[]Must have - Displays list of commissioners' NAMES (extracted from database) with yes/no radio buttons next to each
[]Must have - If yes selected next to a commissioner, a free text box appears underneath with message inviting candidates to specify pre-existing relationship. 
[]Must have - By default, no buttons are selected and the candidate receives an error message if they try to save and continue with any of the buttons unselected
**[]Should have - A button underneath the list that allows the applicant to 'Set all buttons to 'No' - the button could be titled 'I do not have a pre-existing relationship with any of the commissioners'**

**[Ticket Champion]**
Joanne Dixon

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #1066 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Example vacancy: https://jac-apply-develop--pr1087-feature-1066-capture-s74e5f8l.web.app/vacancy/ONqUjAzhDS7rjh6dFJLB/

1. Apply for the vacancy.
2. Complete the "Commissioner Conflicts" section.
3. Check if the answers are saved on the review page.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://github.com/jac-uk/apply/assets/79906532/347f6dce-fc16-41c3-9058-4fc33b09d73d

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by Franceswog — COMMENTED** [review]
In the commissioner conflict page, after  I selected the options , I was unable to save and cotinue. The page was static hence my options were not save neither was it labelled as DONE..

**Review by nickaddy — APPROVED** [review]
Works as described. Was able to go back in and edit multiple times. Default to no button at the bottom works too.

**Comment by HalcyonJAC** [comment]
> In the commissioner conflict page, after I selected the options , I was unable to save and cotinue. The page was static hence my options were not save neither was it labelled as DONE.

@Franceswog Could you provide a screenshot, please?

**Review by Franceswog — COMMENTED** [review]
I carried out this test again but got the same result.  I am still unable to save and continue also the second screen shot shows the form is incomplete hence ;''DONE'' is  unavailable next to commissioner conflict. see  screenshot below..
image

image

**Comment by nickaddy** [comment]
@HalcyonJAC Could you pls amend the first sentence of text at the top of the page to: 

Members of the Judicial Appointments Commission (JAC) come from a wide background to ensure the Commission has a breadth of knowledge, expertise and independence.

**Comment by nickaddy** [comment]
@HalcyonJAC I have requested Welsh translation for the content of this page

**Comment by nickaddy** [comment]
@HalcyonJAC Please see translation below to enable creation of parallel page in Welsh:

Commissioner conflicts
Members of the Judicial Appointments Commission (JAC) come from a wide background to ensure the Commission has a breadth of knowledge, expertise and independence. Are you related to, or known to any of the JAC Commissioners? If you are in any doubt then please select 'Yes' in the list below:
Gwrthdaro buddiannau
Mae Aelodau’r Comisiwn Penodiadau Barnwrol (JAC) yn dod o amrywiaeth eang o gefndiroedd i sicrhau bod gan y Comisiwn wybodaeth, profiad ac annibyniaeth eang. Ydych chi’n perthyn i unrhyw un o Gomisiynwyr y JAC neu a ydynt yn gwybod pwy ydych chi? Os oes gennych unrhyw amheuon dewiswch ‘Ydw’ yn y rhestr isod: 

Please provide details of your relationship.
Rhowch fanylion eich perthynas.

I do not have a pre-existing relationship with any of the commissioners
Nid oes gennyf unrhyw fath o berthynas ag unrhyw un o’r comisiynwyr  

Yes
Ydw 

No
Nac ydw 

Save and continue
Cadw a pharhau

**Review by tomlovesgithub — APPROVED** [review]

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC Please see translation below to enable creation of parallel page in Welsh:
> 
> Commissioner conflicts Members of the Judicial Appointments Commission (JAC) come from a wide background to ensure the Commission has a breadth of knowledge, expertise and independence. Are you related to, or known to any of the JAC Commissioners? If you are in any doubt then please select 'Yes' in the list below: Gwrthdaro buddiannau Mae Aelodau’r Comisiwn Penodiadau Barnwrol (JAC) yn dod o amrywiaeth eang o gefndiroedd i sicrhau bod gan y Comisiwn wybodaeth, profiad ac annibyniaeth eang. Ydych chi’n perthyn i unrhyw un o Gomisiynwyr y JAC neu a ydynt yn gwybod pwy ydych chi? Os oes gennych unrhyw amheuon dewiswch ‘Ydw’ yn y rhestr isod:
> 
> Please provide details of your relationship. Rhowch fanylion eich perthynas.
> 
> I do not have a pre-existing relationship with any of the commissioners Nid oes gennyf unrhyw fath o berthynas ag unrhyw un o’r comisiynwyr
> 
> Yes Ydw
> 
> No Nac ydw
> 
> Save and continue Cadw a pharhau

@nickaddy The Welsh translations have been updated.

**Comment by nickaddy** [comment]
Can't be released yet due to live exercises.

**Review by drieJAC — APPROVED** [review]

**Pull request merged**
