### PR TITLE
#747 Extra options for pupilage

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
Candidates are asked to provide a date completed pupilage if they add barrister qualification to their application. 

They also have the chance to say that they have not completed pupilage, in which case they are asked for a date they were called to the bar and given an option to add details.

Here also they can select that they have not been called to the bar and add details.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context
image
image
image

PREVIEW:DEVELOP

### CODE REVIEW

**Review by HalcyonJAC — APPROVED** [review]
Looks good to me and works fine when I test it locally.

The only thing I noticed is that if a pupilage date is entered and then the 'I did not complete pupilage' box is ticked afterwards, the pupilage date is still saved. This is fine of course providing that the developer doesn't just check for `date == null` or something like that in some other part of the system (i.e. reporting).

Something to be aware of...

image

image

**Comment by warrensearle** [comment]
Hey @tomlovesgithub there's a broken test on this PR... your favourite 😄

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
Just a question, should any of these boxes be 'required'?

I agree with the above review. If for example, the candidate entered a date erroneously, it should be deleted if another box is ticked. Also when the date is entered for 'When were you called to the bar?' question it still displays as 'Date completed pupillage' on the application Review page, in Sent applications and in Admin. Plus I think tests are failing.

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
Hi Tom, I think you need to update the qualifications object in the database, depending on the answers candidates provide in the application form. In RelevantQualifications.vue go through the qualifications and set dates to correct values depending on your checkboxes being true/false. [This is a good example here I think - line 134 onwards](https://github.com/jac-uk/apply/blob/develop/src/views/Apply/CharacterInformation/CriminalOffences.vue). Otherwise your data will look like this:


Qualification1
Qualification2
Qualification3

**Comment by tomlovesgithub** [comment]
Hey @mbrookeswebdev I think you're right here, Ive tried to address it with some frontend validation and clearing of the data, but think there might be a better option here. 
Please have a look and let me know.

**Review by mbrookeswebdev — APPROVED** [review]
I think it works well. 👍   The only thing I would change is what we've discussed re: double negative `notCalledToBar = false`.

**Comment by warrensearle** [comment]
This is working however I think the UX needs a bit of work. In my opinion there are too many moving parts: you tick one box it jumps to somewhere else on the screen and the question you were answering disappears.

Off the top of my head I'd suggest the questions are re-worded to something like:

Have you completed pupillage?
 - Yes   _[if chosen then ask for dates]_
 - No

_[if not completed pupillage then ask the following]_
Have you been called to the bar?
 - Yes  [if chosen then ask for dates]
 - No

**Review by KateMJAC — COMMENTED** [review]
Querying whether the inclusion of 'I was not called to the bar' is appropriate.

Functionality was fine and successfully tested by UTG.

**Review by KateMJAC — COMMENTED** [review]
Hello @tomlovesgithub, I like Warren's suggestions in his comment. 

Can you please update as outlined.

**Review by KateMJAC — DISMISSED** [review]
Hello @tomlovesgithub. I like Warren's suggestions for this ticket. Can you please amend accordingly.

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
Hi Tom, a couple of comments here - 

1. Maybe too picky of me (sorry!), but I think we need to be consistent with the rest of the application and say Yes - No, rather than No - Yes, the flow seems somehow unnatural this way around. 

2. Just going with what Warren suggested to only display request for dates if answer is a 'Yes', it displays both the yes/no question and a request for dates at the same time. 

3. When asked 'Have you completed pupilage?', the date is not required and it is possible to proceed without it, is that the expected behaviour? 

4. If answer 'Yes' to 'Have you completed pupilage?' question changed to a 'No', the date is not cleared and displays in 'When were you called to the bar?' boxes. If you change this date, it is possible to save without an answer to 'Have you been called to the bar?' question but with a date.

5. Maybe it would be good to remove commented out code to shrink the component a little.

RQ1

Another screenshot: 

RQ2

**Comment by mbrookeswebdev** [comment]
Hi @tomlovesgithub It works well except of item 4 on the list above, i.e if you If answer 'Yes' to 'Have you completed pupilage?' question and then change your answer to a 'No', the date for pupilage appears in 'When were you called to the bar?' box. If you change this date, it is possible to save without an answer to 'Have you been called to the bar?' question but with a date.

Relevant-qualifications-Judicial-Appointments-Commission

**Comment by mbrookeswebdev** [comment]
@tomlovesgithub Hi Tom, I think I've fixed it but the preview url won't regenerate.

**Review by KateMJAC — COMMENTED** [review]
I tested this on 02/06 and all worked on Apply as it should, however as there is some further work on Admin that needs to take place I will hold on sending to the UTG.

**Comment by KateMJAC** [comment]
I tested this on 02/06 and all worked on Apply as it should, however as there is some further work on Admin that needs to take place I will hold on sending to the UTG.

**Review by KateMJAC — COMMENTED** [review]
@tomlovesgithub @joy-ade Positive test results at UTG, however, can we realease this with legal exercises open on the platform?

**Comment by tomlovesgithub** [comment]
> @tomlovesgithub @joy-ade Positive test results at UTG, however, can we realease this with legal exercises open on the platform?

this would have a similar impact to the RTF input, as some of these fields are mandatory any candidates applying after this change would have to provide additional information compared to those who applied prior

**Review by mbrookeswebdev — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]
This is working nicely now 👍 
✅ Code reviewed
✅ Tested via preview URL

**Comment by KateMJAC** [comment]
Awaiting action on the admin PR before this can be progressed.

**Review by KateMJAC — COMMENTED** [review]
This has been sent to UTG on 30/06/21 after final changes made by Tom. Will await feedback before final approval. 

Also before this ticket is released consideration needs to be given to how it may/may not impact open exercises.

**Review by HalcyonJAC — APPROVED** [review]

**Review by KateMJAC — COMMENTED** [review]
All required changes at this point made by Tom. 

Sent to the UTG w/c 2th June with no feedback due to sign-in issues. 

Sent to w/c 5 July testers

**Review by KateMJAC — APPROVED** [review]
Positive result at UTG

**Pull request merged**
