### PR TITLE
#1120 BUG: Log in page. Password show/hide button is being called instead of form submit

### LINKED ISSUE #1120: BUG: Log in page. Password show/hide button is being called instead of form submit
The following observation was made during user testing on 6 Dec:

"When logging in, hitting Enter after typing in your password made the password visible (Unhide) rather than signing in which isn't ideal."

**Expected**
If you type in your password and then hit enter the log in form should be submitted

**Actual**
If you type in your password and then hit enter the password you entered is revealed

_Note: I suspect the solution is simply to give the show/hide button a `type="button"` attribute. Though perhaps to change the tab index._

### PR DESCRIPTION
**Pull request by drieJAC**
## What's included?
Added button types to ensure hitting the Enter button triggers the submit instead of the show/hide pwd.

Closes #1120 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

- Got to the login page.
- FIll in the user name.
- Fill in the password and press the Enter button on your keyboard.
- The form should submit instead of the Show/Hide button being triggered.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by warrensearle — APPROVED** [review]
👍

**Review by HalcyonJAC — APPROVED** [review]

**Comment by NormaJAC** [comment]
When I pressed the enter button, nothing happened. 
image

**Review by Franceswog — COMMENTED** [review]
I was able to fill in the  password and hit enter but the  form did not submit itself . 
image

**Comment by warrensearle** [comment]
@drieJAC please merge latest main into this branch so the preview deployment works again (needs the node 20 upgrade)

**Comment by nickaddy** [comment]
@drieJAC Was there supposed to be a preview url or just live testing on Develop?

**Comment by nickaddy** [comment]
@drieJAC This does work, but I've noticed that it takes several seconds to proceed to the next page; is it possible to have one of those whirring circle icons on the **Continue** button so that users know something is happening?

**Review by Franceswog — APPROVED** [review]
This works for me now !

**Pull request merged**
