### PR TITLE
Added extended regex validation to formfield emails

### PR DESCRIPTION
**Pull request by tomlovesgithub**
https://stackoverflow.com/questions/201323/ for source of regex pattern.

### CODE REVIEW

**Comment by warrensearle** [comment]
@tomlovesgithub which issue is this PR created for?

**Comment by warrensearle** [comment]
Hey @tomlovesgithub  the new regex seems to allow multiple @ symbols in the email address. Not sure if this is a problem as such but it makes me wonder if we should be using another regex.
e.g. WHATWG has an email regex (in green box) on the following HTML5 page:
https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type%3Demail)

**Comment by tomlovesgithub** [comment]
hey @warrensearle  i think i may have come across the same regex suggestion you have provided. 
image
I only went against it cause it states its a _**'willfull violation'**_ of the rules which the regex ive inserted should describe.
I've added some tests so we can test email addresses, if you think this might need changing we can certainly do so, however this should allow candidates with complaint yet uncommon email addresses of most types to pass.

**Review by warrensearle — APPROVED** [review]

**Review by mbrookeswebdev — APPROVED** [review]

**Review by mbrookeswebdev — APPROVED** [review]

**Review by HalcyonJAC — CHANGES_REQUESTED** [review]
Let me know once this is ready to review 😄

**Pull request closed without merging**
