### PR TITLE
admin#2248 Global commissioners

### PR DESCRIPTION
**Pull request by warrensearle**
## What's included?
Closes jac-uk/admin/issues/2248

## Who should test?
✅ Product owner
✅ Developers

## How to test?
Check that commissioner conflicts feature works as expected

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by tomlovesgithub — APPROVED** [review]

**Comment by nickaddy** [comment]
@warrensearle Similarly, on this one, am I just testing that the new commissioners appear under commissioner conflicts?

**Comment by nickaddy** [comment]
@warrensearle Are commissioners stored as a single field ((name))?

**Review by nickaddy — APPROVED** [review]
I can see all of the new commissioners in the conflicts list :-)

**Comment by warrensearle** [comment]
> @warrensearle Are commissioners stored as a single field ((name))?

Yes currently they are, for example "Right Honorable Jim Bob". If we wish to order them by surname then we will need to modify how we store the data (e.g. use two fields such as first name and last name)

**Pull request merged**
