### PR TITLE
Security/769 weak passwords allowed in reset form

### LINKED ISSUE #769: Vulnerability – Reset password process allows weak passwords
The password complexity requirements when registering with the platform are different from when resetting a password (for the same platform)

[Here are the password requirements when registering with the platform]

[Here are the password requirements when resetting a password]

Note: In addition, 6 characters is too weak password requirements.

### PR DESCRIPTION
**Pull request by HalcyonJAC**
This PR closes #769 

**Author checklist**

- [x] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [x] Fill in the details below and delete as appropriate
- [x] Be proactive in getting your work approved 💪

---

## What's included?
This change ensures that when someone resets their password its handled in the same way with the same complexity requirements as when they sign up.

A new component has been created that the out-of-band code will be passed to. This component checks the OOB code, and provides it along with a new password the user has specified and then on success instructs the user to sign in with their new password.

We will need to update the email that we send to the user when they request a password reset in `Firebase Console ==> Authentication ==> Templates ==> Reset Password` to the following:

```
https://jac-apply-develop.web.app/confirm-reset-password/?oobCode=code
```
and then this will need have to be added to the other platforms as this change makes its way through.

Its worth noting that the old process will still work even with this change implemented. We might want to turn that off later on.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

- Request a password reset.
- Copy the url after and including the ? mark, although you only *really* need the oobCode parameter.
- Go to whatever application URL you are using to test, with /confirm-reset-password as the page followed by the copied URL parameters.
- e.g locally, for me, I would go to `http://localhost:8181/confirm-reset-password?oobCode=_-RUnWVnYebH_lZ8NXaHUkn2KTbCpIOJjTTBUJ6HJI8AAAF5W3NOzg`
- Change your password
- Ensure your password has indeed changed

- Then try:
  - A code that isn't valid.
  - The code you just got again.
  - No code in the URL.
  - These should all return an error.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work - however it does modify part of the core user journey.

## Additional context

This might redirect to the not found page if any of the following is true:

- The code has been used
- The code was not found in the URL
- Firebase returned any error when ensuring the code is valid.
---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by warrensearle — APPROVED** [review]
Tested and working as described:

✅ was able to change password using the new form
✅ using the same reset url again took me to the error page (below)
✅ using a broken reset url again took me to the error page (below)

image

**Review by mbrookeswebdev — APPROVED** [review]

**Review by KateMJAC — COMMENTED** [review]
@HalcyonJAC this all worked as intended for me. I need to send this to the user testing group and then return to approve. 

A minor question on the content of the email that we receive when requesting a passwork reset. It currently says 'platform-develop' and signs off with 'Your platform-develop team'. What will those be changed to when on production?

**Comment by HalcyonJAC** [comment]
> A minor question on the content of the email that we receive when requesting a passwork reset. It currently says 'platform-develop' and signs off with 'Your platform-develop team'. What will those be changed to when on production?

Hi @KateMJAC - I've requested a password reset on production just now for our account and it comes up as so:

image

However - I think we should change the sender to the JAC or something as just having the email like that isn't ideal.

**Review by tomlovesgithub — APPROVED** [review]

**Comment by HalcyonJAC** [comment]
From name has been updated on develop, staging and production to read as above. 

Adam

**Review by KateMJAC — APPROVED** [review]
Positive result at UTG.

**Pull request merged**
