### PR TITLE
#371 Breadcrumb component

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
A new component for breadcrumbs which uses the routes to auto-generate the breadcrumb

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Visit pages throughout the system and check the breadcrumb component

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by mbrookeswebdev — APPROVED** [review]

**Comment by warrensearle** [comment]
Hey @HalcyonJAC please could you fill in the PR template details (what's included, how to test etc)... and remove anything that's not relevant.

**Review by tomlovesgithub — CHANGES_REQUESTED** [review]
Had a go locally and its working great, might just ask that the [govuk-design kit breadcrumb](https://design-system.service.gov.uk/components/breadcrumbs) is used to style the component

**Comment by HalcyonJAC** [comment]
@tomlovesgithub Thanks, the UI now matches the gov.uk design kit

**Review by lloback — APPROVED** [review]
✔︎

**Review by tomlovesgithub — APPROVED** [review]

**Comment by KateMJAC** [comment]
This has been sent to the UTG. Will update when feedback received.

**Review by KateMJAC — COMMENTED** [review]
This has been sent to the UTG. Update to follow.

**Review by joy-ade — APPROVED** [review]
approved by UTG

**Review by KateMJAC — CHANGES_REQUESTED** [review]
@HalcyonJAC 

The UTG have reported issues on the Character Information section. 

Picture and detail on the ticket. 

Please confirm whether this is intentional or next steps to resolve.

**Comment by HalcyonJAC** [comment]
Hi @KateMJAC 

Thanks - this is a result of the way the routes / urls have been defined for this page. That page does actually exist, but doesn't have any contents. As a result, I've added the ability to override the links within the breadcrumbs so that they point to a different page. In this example, I've pointed it to the summary page for Character Information. I've also tried to find any other examples of this but couldn't find any, so hopefully this is an isolated instance.

**Comment by KateMJAC** [comment]
This has been sent to UTG 05/07/21 after amendments. feedback to follow.

**Review by KateMJAC — APPROVED** [review]

**Review by KateMJAC — COMMENTED** [review]
This has been sent to UTG 05/07/21 after amendments. feedback to follow.

**Pull request merged**
