### PR TITLE
Feature/1204 Mandate NINo field in Personal details section of Application form

### LINKED ISSUE #1204: Mandate NINo field in Personal details section of Application form
## Background
On a recent exercise, a large number of candidates submitted applications without populating the NINo field. The NINo field was also blank in their account so was not copied across. It was agreed at the Ops management meeting on 25 July to make this field mandatory at application level.

## User Story
As an Admin, I would like to mandate the NINo field on the application form so that I have all the information necessary to check for duplicate applications.

## Feature(s) Description
- [x] Mandate completion of the NINo field in the personal details section of the application form
- [x] Remove the `(optional)` text next to the NINo field in the personal details section of the application form

## Acceptance Criteria 
It's done when the NINo field in the application form is mandatory and the (optional) text has been removed from that page.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Nick

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #1204

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

[Example vacancy](https://jac-apply-develop--pr1205-feature-1204-mandate-ypbfz6y4.web.app/vacancy/aD8YKYEYhQbPThjcaKsM/)

Steps:
1. Apply for the vacancy.
2. Go to the Personal details section.
3. Check if the field "National Insurance number" is mandatory.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@HalcyonJAC The `Save and continue` button is greyed out for me irrespective of whether or not the NINo field is populated.

**Comment by HalcyonJAC** [comment]
@nickaddy It might be that you have submitted the application. I have moved your application to draft for this exercise. Could you test it again, please?

**Review by nickaddy — APPROVED** [review]
That works, @HalcyonJAC, thank you :-)

**Review by drieJAC — APPROVED** [review]

**Review by Franceswog — APPROVED** [review]
NI field is mandatory, no issues to report.

**Review by NormaJAC — APPROVED** [review]

**Pull request merged**
