### PR TITLE
Bugfix/TS 341 ASC jump and edit in review

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
Closes https://github.com/jac-uk/ticketing-system/issues/341

- When you edit ASC, the page should not jump around.
- Add the change link to ASC on the review page.

**Note:** Since the ASC and self assessment upload are on the same page, we might need to rethink the UI and flow on the "Self assessment competencies" page.

## Who should test?
✅ Product owner
✅ Developers

## How to test?

[Example vacancy](https://jac-apply-develop--pr1208-fix-ts-341-asc-jump-xpdoava2.web.app/vacancy/x3CJhzZr1MCMMPUdMw93/)

Steps:
1. Apply for the vacancy.
2. Edit ASC on the "Self assessment competencies" page and check if the page doesn't jump around.
3. Go to the review page and check if there is a "Change" link next to "Additional Selection Criteria" that allows you to edit ASC.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context

Demo of preventing from jumping around when you edit ASC:

[video-30275792-54dd8ba4ee350b04cb2b5bd64a1a510e.webm](https://github.com/user-attachments/assets/2aa83435-7508-4012-b6cd-d38ea608363e)

Demo of adding a link to edit ASC

https://github.com/user-attachments/assets/159f96ab-ac60-420e-a8b9-484c089c20a6

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by warrensearle — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC Two questions:

- Should the ASC appear further up in the review section and does this have an impact on where it appears in the panel packs?
- I have completed all sections of the SA upload form, but the content from question 5 is not being copied across correctly, can this be investigated pls?

**Comment by HalcyonJAC** [comment]
> Example vacancy

@nickaddy 
1. Yes, it makes sense to move ASC before "Self assessment with competencies" on the review page. No impact on the panel pack.
2. I have fixed the exercise settings and it should be working now. Could you test it again, please?

**Comment by nickaddy** [comment]
@HalcyonJAC Could you reset my application back to draft so that I can retest?

**Comment by nickaddy** [comment]
@HalcyonJAC I've also noticed that the applications are not visible from the link, neither is it possible to see the applications under the stages tab.

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC I've also noticed that the applications are not visible from the link, neither is it possible to see the applications under the stages tab.

@nickaddy It was because of no applied applications.

**Review by tomlovesgithub — APPROVED** [review]

**Review by nickaddy — APPROVED** [review]

**Pull request merged**
