### PR TITLE
1404 - show fee-paid for fee-paid roles

### PR DESCRIPTION
**Pull request by tomlovesgithub**
# Issue moved to backlog

### CODE REVIEW

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
@tomlovesgithub There is no fee being displayed -

feepaid

**Comment by tomlovesgithub** [comment]
> @tomlovesgithub There is no fee being displayed -
> 
> feepaid

this appears to be happening when there is no pay provided, we should probably consult at design group weather this should be a required field

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
@tomlovesgithub I've just checked again, if I have values in both options on Admin side, it displays the wrong option on Apply, this is the link and a screenshot:

https://admin-develop.judicialappointments.digital/exercises/ws8DOmg9UkBA2KrHnWdl/edit/vacancy
screenshot

**Review by HalcyonJAC — CHANGES_REQUESTED** [review]
Let me know once this is ready to review 😄

**Comment by warrensearle** [comment]
@tomlovesgithub mark this as 'Ready for review' as and when you're ready 😄

**Pull request closed without merging**
