### PR TITLE
Admin # 1271 Show RTF for ASC questions

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
Rich text display of ASC details.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Ensure Rich text is displayed to candidates when viewing ASC questions. - See screen below

## Risk - how likely is this to impact other areas?
🟠 Medium risk - Here we are using v-html to manipulate the DOM directly, we are doing this elsewhere but its worth noting.

## Additional context
image

---
PREVIEW:OFF
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by warrensearle — APPROVED** [review]
Tested and works as expected ✅

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
I can see HTML tags instead of formatted text:

Statement-of-suitability-Judicial-Appointments-Commission

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
StatementOfSuitability.vue and SelfAssessmentCompetencies.vue also need to be updated.

**Review by mbrookeswebdev — APPROVED** [review]

**Comment by KateMJAC** [comment]
This gets an approval from me. However I just need to sling this one to the User Testing Group and when I receive feedback i'll come back in to approve for deployment to production.

**Review by warrensearle — APPROVED** [review]

**Review by KateMJAC — COMMENTED** [review]
After some patchy testing via UTG, I have sent this to the non-legal team who will be using this feature most. 

They will be adding feedback in this Slack channel by the end of the week, so if you need to deploy this in my abscence, please check there first. The team members testing are Sam Marzan-Esher and Lauren Yu.

**Review by HalcyonJAC — APPROVED** [review]
👍 looks fine to me.

**Review by KateMJAC — DISMISSED** [review]
Hello @tomlovesgithub, I have received feedback from the UTG that if the content entered into the Admin ASC free-text field is changed after launch, this is not updated for applications in 'draft' and the changes will only appear for those who are yet to start an application. 

Is it possible to ensure that any edits applied to the Admin ASC free text field after launch, be globally applied to applications in draft on Apply, in addition to those applications now yet started?

**Comment by KateMJAC** [comment]
Sent to UTG today for re-testing after changes.

**Review by KateMJAC — APPROVED** [review]
Positive results at UTG

**Pull request merged**
