### PR TITLE
fix: #1240 Browser info issue on firefox

### PR DESCRIPTION
**Pull request by warrensearle**
## What's included?
We collect browser info when a QT is started. This fixes an error on firefox

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
(see @HalcyonJAC visuals in the comments below)
You will need to set up a QT in admin.
On firefox:
- Log in to Apply > Qualifying Tests
- Click to start the QT
- You should be able to start the QT without any issues

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by HalcyonJAC — COMMENTED** [review]
I checked out develop, and tried starting a test in Firefox and got this error. 

image

I then checked out this branch and retried in Firefox

**Review by HalcyonJAC — APPROVED** [review]

**Review by mbrookeswebdev — APPROVED** [review]
It works great! 👍 

Screenshot 2021-04-14 at 15 05 51

**Review by tomlovesgithub — APPROVED** [review]
Working for me! 👍

**Review by lloback — APPROVED** [review]

**Review by KateMJAC — COMMENTED** [review]
This also worked for me. Will send it over to the UTG and will hopefully get a quick response.

**Review by KateMJAC — APPROVED** [review]
Positive user testing results.

**Pull request closed without merging**
