### PR TITLE
Feature/1097 mandating fields on apply

### LINKED ISSUE #1097: Mandating fields on Apply
**Background**
Create a ticket to mandate all appropriate fields under Work experience, Selection criteria, Eligibility and Character. 
https://app.zenhub.com/workspaces/discovery-650a9b85a29719001aab198a/issues/zh/3

**User Story** 
As a candidate when I want to provide my _Work experience, Selection criteria, Eligibility and Character_, I must answer all the mandatory questions on **Relevant experience, Post-qualification experience, Judicial experience, Gaps in employment, Statement of suitability, Statement of eligibility** and **Self assessment** before being able to move to the next section, it would help if the appropriate questions are made mandatory, so that I do not miss any required answers.

(Sections to be mandated are below)
**Relevant experience** > Job title and Organisation or business name > make the: _Start date_ mandatory

**Post-qualification experience** > Provide details of your career to date including any judicial appointments or quasi-judicial appointments > **make the**: _Law-related tasks in this role_ **mandatory**

**Judicial experience** > Are you a fee-paid or salaried judge? > **make the** _Have you sat for at least x days?_ **mandatory** > **make this**: _Have you sat for at least x days in one or all of these appointments?_ **mandatory**

**Gaps in employment** > dates and details of any gaps in employment you may have > **make the**: _Start date_ **mandatory** > **make the**: _Law-related tasks in this role_ **mandatory**

**Statement of suitability**> Explanation of legal experience >**make this**: _Do you meet this requirement?_ **mandatory**

**Statement of eligibility** > Explanation of legal experience > **make this**: _Do you meet this requirement?_ **mandatory**

**Self assessment**> Additional criteria > **make this**:  _Do you meet this requirement?_ **mandatory**

**Acceptance Criteria** 
Given that I am on the aforementioned sections, when I'm completing the mandatory questions, then I must answer every question before I am allowed to move to the next section.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUhSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb3de280ddd7d04488f723d3120287d2507d58d7/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUxSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6868588336a1aa9b9fb4d83cffa5f2a6f3da576/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVRSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b82ef5bace8e037f78cd413f5ce59bb5f36369a/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abf20bd85086a877fe0a02688d08b20d687684ee/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWZSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23b7a7cb282fe5bfe069acb7819c2f598781ceff/image.png)

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #1097 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Steps:
1. Go to the preview link: https://jac-apply-develop--pr1128-feature-1097-mandati-vkpdzthx.web.app/vacancy/WfzevDfSdwq3NwWBqJFn/
2. Apply for the vacancy
3. Are you a citizen of the UK, the Republic of Ireland or another Commonwealth country? > Choose Yes and continue.
4. Sign in
5. Go to Relevant experience
   - Filling up Job title and Organisation or business name
   - Leave Start Date empty and Save
   - It should appear error message: Please enter a value for Start date  
image

------------------------

1. Go to the preview link: https://jac-apply-develop--pr1128-feature-1097-mandati-vkpdzthx.web.app/vacancy/VGmoNZAKQQnug7cVG9HW/
2. Apply for the vacancy
3. Are you a citizen of the UK, the Republic of Ireland or another Commonwealth country? > Choose Yes and continue.
4. Sign in
5. Go to Post-qualification experience
    - Leave Law-related tasks in this role selection empty and Save
    - It should appear error message: Please enter a value for Law-related tasks in this role
Error:Select at least one task you do in this role
image

6. Go to Judicial experience
    - Are you a fee-paid or salaried judge? Choose Yes 
    - Have you sat for at least x days should be required (not optional)

7. Go to Judicial experience
    - Are you a fee-paid or salaried judge? Choose No
    - Have you sat for at least x days in one or all of these appointments should be required (not optional)

8. Go to Gaps in employment
    - Enter Details, End date
    - Leave Start date, Law-related tasks in this role selection empty, then Save
    - It should appear error messages: 
        - Please enter a value for Start date
        - Please enter a value for Law-related tasks in this role
image
9. Go to Statement of suitability
    - Leave Do you meet this requirement? Empty, then Save
    - It should appear error message: Please enter a value for Do you meet this requirement?
image

10. Go to Statement of eligibility
    - Leave Do you meet this requirement? Empty, then Save
    - It should appear error message: Please enter a value for Do you meet this requirement?
image

11. Go to Self assessment competencies
    - Leave Do you meet this requirement? Empty, then Save
    - It should appear error message: Please enter a value for Do you meet this requirement?
image

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@HalcyonJAC @NormaJAC @MattHowley In the first section - Relevant experience - should the Job title and Organisation name not be mandatory as well?

**Review by Franceswog — APPROVED** [review]
Carried out this test - It all works as expected

**Comment by MattHowley** [comment]
Yes, Job title and Organisation should be mandatory (essentially every field should be, except where not applicable to all candidates e.g. middle names, suffixes, and previous known names, along with the diversity monitoring form for reasons previously discussed).

**Review by NormaJAC — COMMENTED** [review]
I concur with Matt's comment: "Job title and Organisation should be mandatory (essentially every field should be, except where not applicable to all candidates e.g. middle names, suffixes, and previous known names, along with the diversity monitoring form for reasons previously discussed)."

**Review by tomlovesgithub — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]
Code changes look good 👍

**Comment by nickaddy** [comment]
@HalcyonJAC For any instances created under relevant experience, all fields - except for end date - should be mandatory and the _(optional)_ text removed from the page - pls update

**Comment by nickaddy** [comment]
@HalcyonJAC Additionally, in this configuration of answers under Judicial experience, it is possible to get to Done with the final field empty:

**Comment by HalcyonJAC** [comment]
> 1. https://jac-apply-develop--pr1128-feature-1097-mandati-vkpdzthx.web.app/vacancy/WfzevDfSdwq3NwWBqJFn/

@nickaddy This one is done, can see the change in https://jac-apply-develop--pr1128-feature-1097-mandati-vkpdzthx.web.app/vacancy/WfzevDfSdwq3NwWBqJFn/

image

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC Additionally, in this configuration of answers under Judicial experience, it is possible to get to Done with the final field empty:
> 
> 

@nickaddy It seems that the last field is already optional, but without the wording.
I've added the '(optional)' to it. Could you help me to confirm if it's ok ?
https://jac-apply-develop--pr1128-feature-1097-mandati-vkpdzthx.web.app/apply/VGmoNZAKQQnug7cVG9HW/judicial-experience

Thanks
image

**Review by nickaddy — APPROVED** [review]
@HalcyonJAC Looking good, Kow Wei! :-)

**Pull request merged**
