### PR TITLE
#1313 Location preferences

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
There were a few issues with the way that location preferences were being collected, to resolve this i've changed the interface for 'ranked-choice' type questions to be perceptive of one choice per rank. 
This streamlines the way things work and negates the issues.
I've also added numbers to review page to show the rank given to each choice

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Apply to an exercise and fill in your location preferences.
- Observe new interface
- find any bugs?
- Check numbers display next to correct location preference on review page

## Risk - how likely is this to impact other areas?
🟠 Medium risk - I've done a sweep and tried to ensure the changes to ranked-choice will remain compatible with other places its used, from what i found there was only one other item using the ranked choice component. The issues with location preferences would have been present here too so i believe it should be okay.

## Additional context
Include screen grabs, notes etc.

image

image

---
PREVIEW:DEVELOP

### CODE REVIEW

**Review by warrensearle — CHANGES_REQUESTED** [review]
The submit button moves down the page when the check boxes are selected.
See difference between left/right in screen grab below
ranked-choice

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
I think we need numbers next to locations on the Location preferences page for consistency, as we have them on the Review page and on Admin side.

Location-preferences-Judicial-Appointments-Commission

**Comment by tomlovesgithub** [comment]
image
image

Just done some work with the padding to stop stuff jumping around.
Numbers should be appearing next to selections too!

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
I still couldn't see the numbers next to locations, so I've checked out your branch on my local:

Screenshot 2021-05-12 at 17 25 26

**Comment by joy-ade** [comment]
@Kate this looks perfect it can be sent out to UTG.

**Review by lloback — APPROVED** [review]
This is good to go:
image

image

**Review by warrensearle — APPROVED** [review]

**Review by HalcyonJAC — APPROVED** [review]

**Pull request merged**
