### PR TITLE
#1314 admin/additonal legal experience

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
Additional options to allow candidates to add details of judicial undertakings under PQE

## How to test?
- Find an 'legal' exercise 
image
- Make an application to this exercise
-  When selecting 'The carrying-out of judicial functions of any court or tribunal' under 'Post-qualification experience', you should be given a options to input additional info relating to judicial functions

image

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
@tomlovesgithub
It looks good, however:
1. The entered data doesn't show on Review page.
2. When I select 'The carrying-out of judicial functions of any court or tribunal' option, enter values and then de-select this option, the values are still saved in the database.

**Comment by tomlovesgithub** [comment]
Hey Maria, i've addressed the changes you've requested although i'm not sure about removing the info as in building this out i found it was a little easy to accidentally untick, which might frustrate users if it clears their entered info

**Review by lloback — DISMISSED** [review]
I added the information on APPLY but I don't see it on the admin side. I think it is related to this PR as it looks that it is not saving on the database.

image

**Comment by mbrookeswebdev** [comment]
> Hey Maria, i've addressed the changes you've requested although i'm not sure about removing the info as in building this out i found it was a little easy to accidentally untick, which might frustrate users if it clears their entered info

@tomlovesgithub Hi Tom, yes you are right, but that's why we should clear data from the database when they click 'Save and Continue'.

**Comment by tomlovesgithub** [comment]
> * The entered data doesn't show on Review page.
> * When I select 'The carrying-out of judicial functions of any court or tribunal' option, enter values and then de-select this option, the values are still saved in the database.

I can no longer replicate either of these issues, could you check it out and see if its fixed?

**Comment by mbrookeswebdev** [comment]
@tomlovesgithub I've tested again, data for the JO section still stays in the database if clicked 'No', consequently it is displayed on Admin side. I've also noticed that this form is shown on 'Gaps in employment' page but it doesn't save the data in the database.

LegalExp
LegalExp3
LegalExp2

**Comment by HalcyonJAC** [comment]
@tomlovesgithub  For headings, the choice to start each word with an uppercase letter or not is not consistent. Hardly a show-stopper I know, but thought I would notice it:

**Comment by HalcyonJAC** [comment]
If you tick the box so that the new form appears but then leave the form blank the system lets to save it like that. It seems to me that perhaps these fields should become mandatory if they are visible or something.

**Review by HalcyonJAC — CHANGES_REQUESTED** [review]
@tomlovesgithub  For headings, the choice to start each word with an uppercase letter or not is not consistent: specifically; 'Time engaged in this activity' doesn't match the other headings in this respect. Hardly a show-stopper I know, but thought I would notice it:



also...if you tick the box so that the new form appears but then leave the form blank the system lets to save it like that. It seems to me that perhaps these fields should become mandatory if they are visible or something.

**Comment by lloback** [comment]
CLicking on `The carrying-out of judicial functions of any court or tribunal` doesn't ask me to fill extra information. I am using the URL from this PR: https://jac-apply-develop--pr780-1314-admin-additona-sxg2bfsf.web.app/apply/1aYeZX2b7ZF8YICnxwDl/post-qualification-work-experience

**Review by HalcyonJAC — CHANGES_REQUESTED** [review]
Hey @tomlovesgithub 

Couple of points for this one:

1. Perhaps this is my lack of knowledge of the topic, but what is the date field in relation to (the one outside of Dates Engaged in this activity)?
2. Not sure if this is an issue or not but it allowed me to save a start date in the future and and end date in the past.
image

3. Looks like the `<select>` element needs the gov.uk classes for the full time / part time 
image

**Comment by HalcyonJAC** [comment]
It might also be worth adding a note to the end date in case the user is still engaged in the activity and allowing them to leave it blank, but not sure if that is relevant.

**Comment by tomlovesgithub** [comment]
@HalcyonJAC 
Hi, thanks for the diligent review.
- I'm a bit foggy on the exact uses of the data we are collecting but have presented the form to admins and collected feedback; this _current_ version reflects their requests for fields being moved/removed. So as a far as the Date fields i believe this is what's required, but hopefully feedback from YTG will be comprehensive if their are additions/redundancies in the form.
- I could have sorely used a `<DateRange>` or similar component, and think creating one with the logical limitations you've outlined would be useful across the platform, and i had considered it, but deemed it out of scope. I'd be happy to use this as an excuse to get one going however, i think it might be best to park it as a separate issue for now. Happy for a challenge on this
- It appears the previously deployed version didn't have the latest changes, should be updated now!

**Review by HalcyonJAC — APPROVED** [review]

**Comment by HalcyonJAC** [comment]
Thanks @tomlovesgithub - all approved 👍

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
@tomlovesgithub I've started testing by inputting some data, but when I clicked Save and continue some data got deleted and error messages came up, please see the screenshot below:

Screenshot2

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
@tomlovesgithub Please find some feedback below, I've created and annotated a few screenshots:

- I think styling on Post-Qualification experience page could do with a little improvement, perhaps some spacing between buttons and I am not sure if we need this line at the bottom(?). This line also appears on some other pages - for example Qualifications.

prefs4

- On Gaps in Employment page Law-related tasks component is no longer displayed (apologies if it was discussed as a change of requirements).

prefs1

- The data entered by user is displayed in a different order here and some info is missing/or incorrectly labeled.

localprefs2

- As per above, if requirements changed and Law-related tasks component is no longer required for Gaps in employment page, please update Review.

localprefs3

**Comment by mbrookeswebdev** [comment]
@tomlovesgithub can you please fix tests

**Review by mbrookeswebdev — APPROVED** [review]
🎉  👍

**Review by joy-ade — COMMENTED** [review]
Positive test from Product Team out to UTG 19/07/2021

**Review by joy-ade — COMMENTED** [review]
Positive feedbacks from UTG  and awaiting further update on rewording.

**Review by warrensearle — APPROVED** [review]
Code changes look fine to me 👍

**Review by KateMJAC — COMMENTED** [review]
Sent to UTG 27/07 to review final changes

**Review by KateMJAC — CHANGES_REQUESTED** [review]
@tomlovesgithub 
As per Matt's request in the main ticket #1314, the 'Total number of days' questions is only to be displayed if 'fee-paid' or 'voluntary' is selected under 'working basis'. Please amend. 

I am unsure whether this is an issue related to this work or a bug, however I was unable to progress my application when completing the 'Gaps in employment' section. It should allow you to save and move on is you enter data or not. It would not allow me to do so in either circumstance. 

I was also unable to see me application in draft on Admin

**Comment by KateMJAC** [comment]
This has been sent to UTG today after most recent changes were made.

**Review by KateMJAC — COMMENTED** [review]
This has been sent to UTG today after most recent changes were made.

**Pull request merged**
