### PR TITLE
Feature/1040 application form improvements

### LINKED ISSUE #1040: Application form improvements
User story
As a candidate, I would like to be able to input my career history and experience including gaps in employment in a single form so that assessors can easily view my relevant career history.

Background from Roadmap
We have recently established a working group representative of a cross section of JAC staff/teams to look at whether improvements could be made to the application form, not least to better ensure accurate, comprehensive data is collected from candidates.

The proposed improvements are captured on [this Miro board](https://miro.com/app/board/uXjVM1RVfpA=/?userEmail=nick.addy@judicialappointments.digital&track=true&utm_source=notification&utm_medium=email&utm_campaign=add-to-board&utm_content=go-to-board)

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #1040

Design: https://www.figma.com/proto/5XatHx18Pabno2dGrgeYtS/%231040---Application-form-improvements?page-id=0%3A1&type=design&node-id=4-3684&viewport=199%2C308%2C0.13&t=NiGFwt0GsOeMcBAq-1&scaling=min-zoom&starting-point-node-id=4%3A3684&mode=design

Note: The changes will apply to `_applicationVersion 3`.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Example vacancy: 
- https://jac-apply-develop--pr1073-feature-1040-applica-ftrcoggj.web.app/vacancy/ONqUjAzhDS7rjh6dFJLB/
- https://jac-apply-develop--pr1073-feature-1040-applica-ftrcoggj.web.app/vacancy/Y1gSQnCMhbqpA0nHmDaM/

Number of days required experience: 1000

1. Apply for a vacancy.
2. Go to "Previous judicial experience".
3. Check if the form works the same as the design.

Note: The number of days required experience can be set up on admin, e.g.

image

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by nickaddy — CHANGES_REQUESTED** [review]
@HalcyonJAC Looking great!

On the first page - when you are inputting your first entry - can you pls add the following definition in an information box:

Definition of Quasi-judicial:
Quasi-judicial refers to a role similar to that of a judge, such as the chair of an equivalent body for which a legal qualification is required. An equivalent body is one of a quasi-judicial nature for which the powers and procedures should resemble those of a court of law and involve highly complex matters, requiring its members objectively to determine the facts and draw conclusions to reach a reasoned decision. Such decisions could result in the imposition of a penalty, and they are likely to affect the legal rights, duties or privileges of specific parties. Examples could include, but are not restricted to, disciplinary tribunals and conduct hearings for professional standards bodies, the parole board, arbitration and chairs of statutory inquiries. 

Could you also clarify what the minimum number of sitting days is on this exercise so that I can test that additional functionality pls?

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC Looking great!
> 
> On the first page - when you are inputting your first entry - can you pls add the following definition in an information box:
> 
> Definition of Quasi-judicial: Quasi-judicial refers to a role similar to that of a judge, such as the chair of an equivalent body for which a legal qualification is required. An equivalent body is one of a quasi-judicial nature for which the powers and procedures should resemble those of a court of law and involve highly complex matters, requiring its members objectively to determine the facts and draw conclusions to reach a reasoned decision. Such decisions could result in the imposition of a penalty, and they are likely to affect the legal rights, duties or privileges of specific parties. Examples could include, but are not restricted to, disciplinary tribunals and conduct hearings for professional standards bodies, the parole board, arbitration and chairs of statutory inquiries.
> 
> Could you also clarify what the minimum number of sitting days is on this exercise so that I can test that additional functionality pls?

@nickaddy 

1. I have added the definition underneath the question. 

    image

2. The minimum number of sitting days can be set up on admin.

    image

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC I'm waiting for Matt's answer to a question, when I have that I will share a list of the changes requested by the working group. We have plenty of time to get this right as we will not be able to make it live on production until January, due to consecutive exercises running until then.

**Comment by nickaddy** [comment]
@HalcyonJAC Sorry to keep you waiting on this. I have summarised the changes into [this document](https://docs.google.com/document/d/1olZG18aqk-CktmEHo1zHd0HvrEydFaNJ/edit?usp=sharing&ouid=106025876472425620100&rtpof=true&sd=true). Could you please implement this week? Give me a shout if any of the requests are unclear. No need to send back to UT, but can you let me know when complete and I will recirculate to the working group.

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC Sorry to keep you waiting on this. I have summarised the changes into [this document](https://docs.google.com/document/d/1olZG18aqk-CktmEHo1zHd0HvrEydFaNJ/edit?usp=sharing&ouid=106025876472425620100&rtpof=true&sd=true). Could you please implement this week? Give me a shout if any of the requests are unclear. No need to send back to UT, but can you let me know when complete and I will recirculate to the working group.

@nickaddy The items in the word document have been implemented. Could you test them, please?

**Review by nickaddy — CHANGES_REQUESTED** [review]
There are still a few points to address:

- Can the 'or' and tickbox appear on the same line as shown: 
image

- If the law-related tasks is later changed to non-judicial options, the number of sitting days for that post should be deleted; they are still being counted and appearing on the front of the card
- The guidance text to explain only positive integers can be input into the sitting days field and restrict input to positive integers only
- It is possible to enter the characters 'e' and '-' in the sitting days field - can it be limited to 0123456789 only?

**Comment by HalcyonJAC** [comment]
> There are still a few points to address:
> 
> * Can the 'or' and tickbox appear on the same line as shown:
>   image
> * If the law-related tasks is later changed to non-judicial options, the number of sitting days for that post should be deleted; they are still being counted and appearing on the front of the card
> * The guidance text to explain only positive integers can be input into the sitting days field and restrict input to positive integers only
> * It is possible to enter the characters 'e' and '-' in the sitting days field - can it be limited to 0123456789 only?
> 
> Everything else seems to be in order, thanks.

@nickaddy These issues have been fixed. Could you test it again, please?

**Comment by nickaddy** [comment]
@HalcyonJAC There is one minor glitch: when you tick the 'tick if still ongoing' box, the Month and Year boxes should disappear (and reappear if box unticked.) Can you let me know when that's done and I'll share with Matt for checking, thank you!

One other question: are we missing any Welsh translation for this that you're aware of?

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC There is one minor glitch: when you tick the 'tick if still ongoing' box, the Month and Year boxes should disappear (and reappear if box unticked.) Can you let me know when that's done and I'll share with Matt for checking, thank you!
> 
> One other question: are we missing any Welsh translation for this that you're aware of?

@nickaddy I have fixed it. Could you test it again, please?
There are some new texts and we need to update the Welsh translations. I will make a list  and send it to you later.

**Review by nickaddy — APPROVED** [review]
Looks great, Ryan, thank you for all your work on this ticket. Hopefully Matt agrees!

**Comment by HalcyonJAC** [comment]
@nickaddy Here is the list of the new texts that need Welsh translation in this PR.

[application form improvements - new texts.xlsx](https://github.com/jac-uk/apply/files/13237488/application.form.improvements.-.new.texts.xlsx)

**Comment by nickaddy** [comment]
@HalcyonJAC Text send for Welsh translation; @Franceswog will share with you when received.

**Review by MattHowley — CHANGES_REQUESTED** [review]
Looking really good Ryan. Just a few points from me:

1. Employment Gap. We additionally need to ask 'Were you involved in law related activities during this time?' Yes/No

If a candidates selects 'yes' we then need to list the law related activities and ask candidates to 'Select all the tasks that apply'

The carrying-out of judicial functions of any court or tribunal
Acting as an arbitrator
Practice or employment as a lawyer
Advising on the application of the law
Assisting persons involved in proceedings for the resolution of issues arising under the law
Acting as mediator in connection with attempts to resolve issues that are, or if not resolved could be, the subject of proceedings
Drafting documents intended to affect persons' rights or obligations
Teaching or researching law
None of the above - Any activity that, in the relevant decision-maker's opinion, is of a broadly similar nature to those listed above

2. Previous judicial experience. When a candidate ticks 'The carrying-out of judicial functions of any court or tribunal', the help text to the question 'How many sitting days have you accumulated in this post?' currently states: 'Only positive integers can be input into the sitting days field. If the number of days is 100 or more, an approximate figure will suffice.'

Could this text be amended to state 'Only numerical digits can be input into the sitting days field. If the number of days is 100 or more, an approximate figure will suffice.'

3. Previous judicial experience. When candidates are asked to provide details of how they have acquired the necessary skills in some other significant way, the words in bold need to be removed from the text: 'As you have indicated you have less than 1000 **number of** sitting days across all judicial and/or quasi-judicial appointments, please provide details of how you have acquired the necessary skills for this role in some other significant way.'

In addition, a small point only, if a candidate doesn't enter any text to explain how they've gained the necessary skills, they can press the back button twice and the platform will consider the post qualification experience section complete and the candidate will be able to submit the application without having input any information

**Comment by HalcyonJAC** [comment]
@MattHowley Thank you for the feedback.

1. If it’s an employment gap, do we also collect the answers to the questions below when a candidate ticks 'The carrying-out of judicial functions of any court or tribunal' ?

    - Is this a judicial or quasi-judicial post?
    - How many sitting days have you accumulated in this post?
    - Is a legal qualification a requisite for appointment?
    - Please outline the powers, procedures and main responsibilities

    image

    image


3. The text has been updated.
4. The words "number of" have been removed.
5. This bug has been fixed.

**Review by MattHowley — CHANGES_REQUESTED** [review]
Hi @HalcyonJAC - it's getting there, thank you! In terms of employment gaps:

1. After the start and end dates, we need to include a text box for 'Details' so candidates can outline what they were doing during this period. 
2. The law related tasks says optional (which is good), but if you don't select anything red warning text states 'Select at least one task you do in this role'
3. The guidance text for the law related tasks currently states 'Select all tasks you do in this role...' As it relates to a gap in employment rather than a role, could this be changed to 'If you were engaged in law related activities during this time, please select all the relevant tasks...'
4. If a candidate ticks 'The carrying-out of judicial functions of any court or tribunal' I would suggest they are not asked supplementary questions when it relates to a gap in employment

**Comment by HalcyonJAC** [comment]
> Hi @HalcyonJAC - it's getting there, thank you! In terms of employment gaps:
> 
> 1. After the start and end dates, we need to include a text box for 'Details' so candidates can outline what they were doing during this period.
> 2. The law related tasks says optional (which is good), but if you don't select anything red warning text states 'Select at least one task you do in this role'
> 3. The guidance text for the law related tasks currently states 'Select all tasks you do in this role...' As it relates to a gap in employment rather than a role, could this be changed to 'If you were engaged in law related activities during this time, please select all the relevant tasks...'
> 4. If a candidate ticks 'The carrying-out of judicial functions of any court or tribunal' I would suggest they are not asked supplementary questions when it relates to a gap in employment

Thanks @MattHowley. These issues have been sorted. Could you test it again, please?

**Review by MattHowley — APPROVED** [review]
Hi @HalcyonJAC - magnificent! That all looks good to me, thanks Ryan 👍

**Comment by nickaddy** [comment]
@HalcyonJAC Now that Matt has approved the final changes, can this ticket be closed and merged on Develop? It cannot be released on production until January.

**Review by NormaJAC — COMMENTED** [review]
Seen

**Comment by warrensearle** [comment]
Hey @HalcyonJAC could you just confirm whether if this code went live today, say, it would change the application form for any current exercises (using application version 2 or less)?

I think the answer is no it wouldn't have any impact. If that's the case then let's get this merged asap otherwise the code is going to gather cobwebs and become trickier to merge (there is already one conflict to sort).

@nickaddy @MattHowley FYI

**Comment by HalcyonJAC** [comment]
> Hey @HalcyonJAC could you just confirm whether if this code went live today, say, it would change the application form for any current exercises (using application version 2 or less)?
> 
> I think the answer is no it wouldn't have any impact. If that's the case then let's get this merged asap otherwise the code is going to gather cobwebs and become trickier to merge (there is already one conflict to sort).
> 
> @nickaddy @MattHowley FYI

Thanks @warrensearle. I have double-checked that it will not make an impact on the current applications.

**Pull request merged**
