### PR TITLE
Epic [ admin#2141 ] Embedding Pre-Selection Day Questionnaires on the Platform

### LINKED ISSUE #1067: Capture panel conflicts
**User Story**
As an applicant, I would like to specify any panel conflicts so that this can be taken into account during my application.

**[History/context]**
Currently, panel conflicts are captured on Google Forms, but the objective is to embed this functionality on the platform. 
We would like to provide candidates with the opportunity to declare any conflicts they have with the panel on their application so that this information can be taken into account.

**Feature**
Ask the candidate to declare any conflicts with panellists. If there are conflicts then collect details for each.

Task list:
[ ] Form component
[ ] Review component

We should present to the candidates a list of the panellists names from the database with the option to select a yes/no selection button for each one.
Underneath the list, there is a text box for candidates to enter details of conflicts. This appears if candidate selects 'yes' next to any of the panellists.

[Miro board ](https://miro.com/app/board/uXjVNez9BuM=/?moveToWidget=3458764567213574345&cot=14)

**[Acceptance Criteria]**
When I am on the "Additional information" page, I can see the panel conflicts section.
I can choose a panellists name by clicking on the yes/no button.
I can add panel conflicts information in the text box.

### LINKED ISSUE #1088: Pre-selection day questionnaire pages
**Feature**
A new set of pages to collect Pre-selection day (PSD) data from candidates.
Here, we are setting up the pages, the navigation between them and ensuring that all pages can only be accessed by candidates invited to provide PSD data.

**To do**
- [x] Task list page (see miro e.g. `/forms/{formId}`)
- [x] Template / pattern for individual PSDQ forms/parts
- [x] Review page
- [x] Confirmation page
- [x] Add a "Pre Selection Day Questionnaire" button to the applications list and the application view/review page

Note: the individual forms will be built under separate tickets

[Miro Board](https://miro.com/app/board/uXjVNez9BuM=/?moveToWidget=3458764567211511403&cot=14)

### LINKED ISSUE #1089: Transfer character check functionality to PSD
**Feature**
The existing character check functionality is to be merged/ported across to PSD. All forms should solely be available here.

**Task list**
- [x] Move existing character check forms to PSD

### LINKED ISSUE #1090: Reconfirm commissioner conflicts
**Feature**
Re-ask the candidate for any commissioner conflicts; their situation may have changed since submitting their application.

**Task list**
- [x] Make use of existing form and review components
- [x] Amend guidance text to "Please update this section to take into account any changes since you submitted your application"

### LINKED ISSUE #1091: Reconfirm reasonable adjustments
**Feature**
Ask the candidate to reconfirm any adjustments they require with regards to selection day.

**Task list**
- [x] Form component
- [x] Review component
- [x] Amend guidance text to "Please update this section to take into account any changes since you submitted your application"

### LINKED ISSUE #1092: Reconfirm location and jurisdiction preferences
**Feature**
Ask the candidate to reconfirm their location and jurisdiction preferences in case these have changed since their application was submitted.

**Task list**
- [ ] Form component
- [ ] Review component
- [ ] Amend guidance text to "Please update this section to take into account any changes since you submitted your application"

### LINKED ISSUE #1093: Reconfirm Welsh posts
**Feature**
Ask the candidate to reconfirm their desire to be considered for postings in Wales.

**Task list**
- [ ] Form component
- [ ] Review component
- [ ] Amend guidance text to "Please update this section to take into account any changes since you submitted your application"

### LINKED ISSUE #1096: Candidate Availability
**Feature**
Ask the candidate to confirm which days (and locations) they can be available on.

**Task list**
- [x] Form component
- [x] Review component

Linked to [#1065](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/apply/1065)

### PR DESCRIPTION
**Pull request by warrensearle**
## What's included?

All Apply functionality for epic jac-uk/admin/issues/2141 Embedding Pre-Selection Day Questionnaires on the Platform.

The following features are included:

- [ ] #1088 Pre-selection day questionnaire pages
- [ ] #1067 Capture panel conflicts
- [ ] #1096 Capture candidate availability
- [ ] #1091 Reconfirm reasonable adjustments
- [ ] #1089 Transfer character checks to PSD
- [ ] #1090 Reconfirm commissioner conflicts
- [ ] #1093 Reconfirm welsh posts
- [ ] #1092 Reconfirm location and jurisdiction preferences

_Note_
_During development this branch/PR will be used as the 'base' for all feature work.
Individual features will be developed in branches based off of this one, tested and then merged into this base branch.
Full testing of the epic will happen under this PR_

Closes #1088
Closes #1067
Closes #1096
Closes #1091
Closes #1089
Closes #1090
Closes #1093
Closes #1092

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

For all of the following tests please use the following url:
https://jac-apply-develop--pr1107-epic-admin-2141-pre-5toabr5h.web.app/

and log in using one of the following email addresses (password: 1qazZAQ!1qaz):
- application-0001@jac-dummy-email.jac
- application-0002@jac-dummy-email.jac
- application-0003@jac-dummy-email.jac
- application-0004@jac-dummy-email.jac
- application-0005@jac-dummy-email.jac
- application-0006@jac-dummy-email.jac
- application-0007@jac-dummy-email.jac
- application-0008@jac-dummy-email.jac

### #1088 Pre-selection day questionnaire pages - PT 1
 - log in to Apply and navigate to the Applications list
 - observe that there is a 'Pre Selection Day Questionnaire' button next to the relevant application and click on it
 - observe that the task list has a list of tasks to complete and a disabled Review button
 - follow the links on the task list and save each page (some will be blank pages at the moment)

### #1067 Capture panel conflicts
Starting on the pre selection day questionnaire task list:
1. Follow the link to 'Panel conflicts'
2. Complete the form (try identifying a conflict and other scenarios)
3. Click 'Save and continue' and check Panel conflicts is marked as done

### #1096 Capture candidate availability
Starting on the pre selection day questionnaire task list:
1. Follow the link to 'Candidate availability'
2. Complete the form (try choosing no, some or all dates)
3. Click 'Save and continue' and check Candidate availability is marked as done

### #1091 Reconfirm reasonable adjustments
Starting on the pre selection day questionnaire task list:
1. Follow the link to 'Reasonable adjustments'
2. Complete the form
3. Click 'Save and continue' and check Reasonable adjustments is marked as done

### #1089 Character checks
Starting on the pre selection day questionnaire task list:
1. Follow the link to 'Character checks'
2. Check if you can complete the character checks.
3. Click "Save and continue" and check if "Character Checks" is marked as "DONE"

### #1090 Reconfirm commissioner conflicts
Starting on the pre selection day questionnaire task list:
1. Follow the link to 'Commissioner conflicts'
2. Complete the form
3. Click 'Save and continue' and check Commissioner conflicts is marked as done

### #1093 Reconfirm welsh posts
Starting on the pre selection day questionnaire task list:
1. Follow the link to 'Welsh posts'
2. Complete the form
3. Click 'Save and continue' and check Welsh posts is marked as done

### #1092 Reconfirm location and jurisdiction preferences
Starting on the pre selection day questionnaire task list:
1. Follow the link to 'Location preferences'
2. Complete the form
3. Click 'Save and continue' and check Location preferences is marked as done
4. Follow the link to 'Jurisdiction preferences'
5. Complete the form
6. Click 'Save and continue' and check Jurisdiction preferences is marked as done

### #1088 Pre-selection day questionnaire pages - PT 2
Starting on the pre selection day questionnaire task list:
 - notice when all tasks are DONE that the Review button becomes enabled, then click on it
 - notice that the review screen has a section for each task/part of the Pre Selection Day Questionnaire and that there is a Change link next to each part
 - also notice there is a Submit button on the review screen
 - click each of the Change links and check that it goes to the correct form
 - navigate back to the Review screen and click the Submit button 
 - notice that there is a confirmation screen
 - check that no further changes are allowed to the form - e.g. by navigating back to the Review screen, the task list or to the individual forms

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@warrensearle I'm not seeing the PSDQ button:
image

**Review by drieJAC — APPROVED** [review]

**Comment by Franceswog** [comment]
I was able to complete the PSDQ and successfully submitted it . However, I could still make changes to personal details, professional details and consent details. The other sections of the test all have the 'Done' flag.

**Comment by nickaddy** [comment]
Feedback from UT, could the following be addressed tomorrow (Friday 22/12) so that we can close this epic pls?

- [ ] Candidate availability @warrensearle - Currently possible to submit having chosen no dates

- [ ] Character checks @HalcyonJAC - Professional details page appears scrolled down to the bottom-  title is off screen, same for Consent page

- [ ] Commissioner conflicts @HalcyonJAC - Can the ‘I do not have any conflicts…’ button look more like a button? At the moment it just looks like text with a line underneath

- [ ] Welsh posts @tomlovesgithub - Questions 2 and 3 should appear only if ‘yes’ is selected in question 1, also If you try to Save and continue without answering all questions, nothing happens, but there is no error message

- [ ] Review section @warrensearle When you click change to edit candidate availability, it is possible to edit but it takes you back to the original PSDQ screen on completion – this applies to all review sections - it should return to the review page after editing

**Comment by warrensearle** [comment]
@nickaddy some of the tasks in your list (those against my name) have been addressed now

**Review by HalcyonJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Review by nickaddy — APPROVED** [review]
What can I say, except let's get the champagne out! Great work everyone :-)

**Pull request merged**
