### PR TITLE
323 - Vaccany Detail header missing padding

### PR DESCRIPTION
**Pull request by crablab**
Adding back the missing padding (with the appropriate class)

### CODE REVIEW

**Comment by warrensearle** [comment]
Hey @crablab I think the spacing issue is site-wide. Therefore I suspect the spacing could be included (again?) in the main template, or the header, rather than adding it to every page.

**Comment by crablab** [comment]
Hey @warrensearle 
Interesting :thinking:  I couldn't reproduce this in that case. 

Do you have examples of any other pages this is affecting? 

To add context, the way I fixed this was by comparing classes from other pages against the single page I knew of that had issues. Happy to look again if I've missed something!

**Comment by warrensearle** [comment]
Hey @crablab 

> Do you have examples of any other pages this is affecting?

I sure do ;-)

Sign in:
Screenshot 2020-07-16 at 13 01 03

Create an account:
Screenshot 2020-07-16 at 13 01 10

Check you're eligible:
Screenshot 2020-07-16 at 13 01 57

Eligibility fail:
Screenshot 2020-07-16 at 13 02 06

New application process:
Screenshot 2020-07-16 at 13 01 50

**Comment by crablab** [comment]
:thinking: I had been unable to reproduce it on those pages. I'll fix them too. I think browser caching isn't helping here.

**Comment by crablab** [comment]
@warrensearle Fixed :+1:

**Pull request merged**
