### PR TITLE
Supporting changes for #admin 1244 Equal Merit Tie-breaker tests.

### PR DESCRIPTION
**Pull request by HalcyonJAC**
---
PREVIEW:DEVELOP

### CODE REVIEW

**Comment by HalcyonJAC** [comment]
FYI - This pull request is badly named as _updated package lock_. The changes are to support the Equal Merit Tie-breaker tests.

**Review by warrensearle — APPROVED** [review]
The changes here look good to me 👍

**Review by mbrookeswebdev — APPROVED** [review]

**Comment by KateMJAC** [comment]
@HalcyonJAC can you please update the apply PR. thank you.

**Comment by KateMJAC** [comment]
@HalcyonJAC can you please regenerate the PR preview URL please.

**Comment by HalcyonJAC** [comment]
@KateMJAC I have resolved some conflicts with the `main` branch (which used to be called `develop`) and regenerated the preview URL

**Review by joy-ade — APPROVED** [review]
Approved by product team

**Review by KateMJAC — COMMENTED** [review]
Sent to UTG for feedback. Update to follow.

**Comment by KateMJAC** [comment]
Sent to the UTG a second time as UTG did not test last week.

**Review by KateMJAC — COMMENTED** [review]
Ticket not tested by prevous week's testers. 

Sent to UTG on 29/06/21. Awaiting feedback.

**Review by KateMJAC — COMMENTED** [review]
I positive test confirmed. Sent to w/c 5 July testers for more feedback.

**Review by joy-ade — COMMENTED** [review]
UTG 21/07/2021

**Review by joy-ade — COMMENTED** [review]
@HalcyonJAC feedback from UTG I was able to create the emp tie breaker and sit the test as applicant. I then closed the test and hit close and score after which I went to reports but cannot see an option to create a report on the tie breaker.

**Review by KateMJAC — APPROVED** [review]

**Pull request merged**
