### PR TITLE
Feat/apply 1186 correct text in eligibility information on tribunal exercises

### LINKED ISSUE #1186: Correct text in Eligibility information on Tribunal exercises
## Background
On Legal Tribunal exercises, an additional question is triggered under Eligibility as shown below. The text relating to schedule 3(d) eligibility is not appearing correctly and needs to be corrected on both Admin and Apply sites. There is [a separate ticket for Admin](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2425).

## Feature(s) Description
- [ ] Under qualifications for Legal Tribunal exercise, if schedule 3(d) has been selected, the text in the first question should be corrected to `Are you applying under Schedule 3(d)?`

## User Testing Steps
Internal testing only.

## Feature Champion
Nick

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
closes #1186 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Apply with this vacancy: https://jac-apply-develop--pr1188-feat-apply-1186-corr-k9tmuo39.web.app/vacancy/X2tDg5AKt18xvzBRJFYW/
- Go into the `Relevant qualifications` section, the text should be `Are you applying under Schedule 3(d)?`

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@KoWeiJAC Why is this not showing the changes that Tom made - adding the None of the above option - that have already been released? 
image

**Review by NormaJAC — APPROVED** [review]
The text now says 'Are you applying under Schedule 3(d)?'

**Review by Franceswog — APPROVED** [review]
No issues to report, looks good ..

**Comment by nickaddy** [comment]
@KoWeiJAC I'm also not sure why 'optional' is appearing after the question - it is mandatory or should be:
image

**Review by HalcyonJAC — APPROVED** [review]

**Comment by KoWeiJAC** [comment]
@nickaddy 
I had following changes:
- Merge the `None of above` changes of this PR: https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/apply/1187
- Made the Are you applying under Schedule 2 or 3(d) question to be mandatory
Could you help me to review it again ? Thanks

**Review by nickaddy — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Review by drieJAC — APPROVED** [review]

**Pull request merged**
