### PR TITLE
Feature/589 firebase app check

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
This change imports the firebase app check into the admin repository and works around an issue with the application not building on some machines or environments.

## Who should test?

✅ Developers

## How to test?
Add the public recaptcha key below into your .env.develop.local file and make some requests. Ensure that these show in the verified requests on the firebase project settings => app check in the firebase console.

`6LcVn5kbAAAAADZNrAZCfEJ2KOCyS--Alb7eHvXG`

## Risk - how likely is this to impact other areas?

🟠 Medium risk - this does change code that is shared with other areas *however* enforcement isn't enabled for form requests and firebase functions/firestore changes as yet.

## Additional context

---
PREVIEW:DEVELOP

This work can only be previewed on localhost as of now.

### CODE REVIEW

**Review by warrensearle — CHANGES_REQUESTED** [review]
@HalcyonJAC is fixing merge conflicts

**Review by warrensearle — APPROVED** [review]
Code looks good though seems to cover more than just Firebase App Check... looks like there's a change/fix for `JsPDF` too. Please make sure you link to any relevant ticket. Should the JsPDF change be applied to Admin too, if it hasn't already?
👍

**Comment by HalcyonJAC** [comment]
> Code looks good though seems to cover more than just Firebase App Check... looks like there's a change/fix for `JsPDF` too. Please make sure you link to any relevant ticket. Should the JsPDF change be applied to Admin too, if it hasn't already? 👍

Ok I am not sure how they ended up in this PR to be honest. However, the following PR was deployed some time ago which upgraded JSPdf a major version: https://github.com/jac-uk/apply/pull/716/files. This no doubt had breaking changes and it looks like the PDF code here fixes that. I will create a new PR and move the PDF code to that. I will also create a similar PR on the admin repo.

**Comment by HalcyonJAC** [comment]
Note: I have removed the PDF code changes from this PR now and created a new PR for them, plus a similar PR in the admin repo

**Pull request merged**
