### PR TITLE
1734/ Give vue components names

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
See Title - Helps with debugging, locating files, and with vue dev tools. - 
Hopefully i haven't missed anything or broken anything.

## Who should test?
✅ Developers

## How to test?
????

## Risk - how likely is this to impact other areas?
🟠  Low risk -  unlikely this broke anything

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by warrensearle — DISMISSED** [review]
Just a few names to use leading capital character - see my comment for one, plus the auto-comments from github

**Review by andrew-isaac — COMMENTED** [review]
Not sure why I am on the approve list but I will his yes when Warren and Lee etc are content

**Comment by tomlovesgithub** [comment]
> @tomlovesgithub this PR has a lot of unrelated changes. We need to have confidence that when we review, we can then merge and nothing wrong will happen.
> 
> There are some unrelated changes that cannot be added on the same PR. This PR was supposed to be a continuation of admin/1734. Check the list that is not exhaustive and each one should have a task associated and a PR:
> 
> 1. Changes to configuration files
> 2. Changes to lint files
> 3. changes to firebase
> 4. upgrade version of dependencies on the package.json
> 5. Adding names to the components, which was the tasks, and the majority are blank ""
> 6. unit testing
> 7. adding commas to json files
> 
> I would suggest that you CLOSE this PR (don't lose track of it and all the changes that you made - they are fine); create a new branch for the task 1734 and do the work related to that one, THEN, create tasks for the other issues and add smaller PRs with less code changes in each.

Strangely i remember replying to this but cant find the response - I made a bad merge and caused alot of pollution, this is no longer the case, please re-review when possible.

**Review by warrensearle — APPROVED** [review]
Looks good to me 👍

**Review by HalcyonJAC — APPROVED** [review]
👍

**Pull request merged**
