### PR TITLE
Feature/1243 2FA - Implement 2FA When Logging In And Add 7 Days Timeout

### LINKED ISSUE #1243: 2FA - Implement 2FA When Logging In And Add 7 Days Timeout
## Background
As part of implementing 2FA we would like to force the user to have an email or SMS sent to them when logging in. This will need to be repeated every 7 days.

## User Story
As a candidate, I need to confirm my identity by email or SMS every 7 days. Look into how this is implemented in firebase. 

## Benefit(s) to user (if not already clear from User story)
Increased security to ensure the identity of the user.

## Feature(s) Description
- [x] Create a backend callable function which tells the frontend whether sms verification is required (ie 7 days has elapsed since last verification via sms/email)
- [x] Implement 2FA via email or SMS for users and ensure they must reconfirm after 7 days

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #1243 

Related PR: [digital-platform: Feature/1231 Setup SMS Service #1233](https://github.com/jac-uk/digital-platform/pull/1233)

- Add the two-factor authentication settings to Firestore:

  /settings/candidateSettings

  ```js
  twoFactorAuth: {
    enabled: true,
    timeoutDays: 7
  }
  ```

  `enabled`: whether 2FA is enabled on the system level
 `timeoutDays`: how often 2FA needs to be performed

- Implement 2FA via SMS for users.
- Ensure users must reconfirm every 7 days.

## Who should test?
✅ Product owner
✅ Developers

## How to test?

[Preview URL](https://jac-apply-develop--pr1248-feature-1243-2fa-log-u7t35fsh.web.app/)

#### Ensure your UK mobile number is verified on the profile page
1. Log in via the preview URL and go to the "Your profile" page.
2. Edit the "UK Mobile phone number" field and verify your UK mobile number.
3. Once it's verified, 2FA is enabled.
4. Each time the mobile number field is updated, users will be forced to log out. 

#### Check if 2FA is enabled when logging in
1. Go to the login page and enter your email and password.
2. Check if a pop-up appears and asks you to enter the verification code.
3. Check if you receive the verification code (6-digit) sent by SMS.
5. Check if the verification code is working.
6. Check if the resend button is working.

#### Check if 2FA is repeated every 1 day (for testing)
1. Log out and then log in again.
2. Check if you can log in directly without 2FA within 1 day.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://github.com/user-attachments/assets/5730353e-3323-495b-b8d9-2bdbcaeaeb86

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by tomlovesgithub — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC I'm afraid this is not working for me at all: I'm able to log in but do not receive a verification code and when I click resend, I get an Error button. Can demo if that would help?

**Comment by nickaddy** [comment]
@HalcyonJAC When I try with my jud apps.digital account, the verification message pops up when I click continue from the sign in page.

**Review by NormaJAC — APPROVED** [review]

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC I'm afraid this is not working for me at all: I'm able to log in but do not receive a verification code and when I click resend, I get an Error button. Can demo if that would help?

@nickaddy I have redeployed the cloud functions. Could you test it again, please?

**Comment by nickaddy** [comment]
There needs to be a different modal for when you log back in to your account once you have already verified your number. At the moment it looks like this:

image

This is not correct because they've already verified their number, now they are logging in and being asked for 2-Factor authentication. The title should say Two-factor authentication and after the first line, I think we should add the text (even if it is obvious) 'Please enter the code in the box below'

**Comment by HalcyonJAC** [comment]
@nickaddy I have updated the title and text. Could you test it again, please?

**Review by Franceswog — APPROVED** [review]

**Pull request merged**
