### PR TITLE
688 refactor review and tasklist vue components

### PR DESCRIPTION
**Pull request by HalcyonJAC**
**Author checklist**

- [x] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [x] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---

## What's included?

Please see parent ticket: https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/apply/688

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

Test every section of the application form.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
I haven't used mixins before, it looks good 👍  A small issue however I've found is this

Screenshot 2021-05-05 at 13 58 43

[This is the local link](http://localhost:8181/apply/5S9fRWlCDr5m9AZmETFa/review)

**Review by warrensearle — APPROVED** [review]
Code changes look good to me - a giant leap forward from what was there previously 👍 
(Note: I have reviewed the code changes but not tested in browser)

**Comment by KateMJAC** [comment]
@HalcyonJAC sorry, but can you please regenerate the PR preview URL?

**Comment by HalcyonJAC** [comment]
Hi @mbrookeswebdev I couldn't replicate the error you've shown above. Please could you list the steps you went through to generate it? Thanks

**Comment by mbrookeswebdev** [comment]
@HalcyonJAC I've just re-tested and couldn't reproduce the error, I'll approve 👍

**Review by mbrookeswebdev — APPROVED** [review]

**Review by lloback — APPROVED** [review]
This is good to go. Tested on the browser and it looks fine.

**Review by KateMJAC — COMMENTED** [review]
This has been sent to the UTG for testing. Feedback to follow.

**Review by KateMJAC — CHANGES_REQUESTED** [review]
@JeremykJAC @HalcyonJAC Positive response from UTG in relation to main application, however we received the following feedback in relation to the uploads section: 

Donna Toms-sheridan  6:05 PM

@Kate Malone Hi, I have tested ticket 688. There were no issues with the application I completed. I did replace the uploaded self assessment in admin develop and when I tried clicked on the selaf assessmnet link to see if the new document had uploaded this appeared:

  "error": {
    "code": 403,
    "message": "Permission denied. Could not perform this operation"
  }
}
I pressed the back button and then went to the self assessment document link to see if it had been replaced, and it had. I have done this 3 times to see if the same error message appears and then to see if the document has actually been replaced when you press the back button, and each time, the document has been replaced.

Is this an error in relation to the work done for this ticket? 

Thank you

**Comment by HalcyonJAC** [comment]
Note that the preview URL is working, and doesn't expire until 18/06/2021:

https://jac-apply-develop--pr772-feature-688-refactor-o2t2e7vo.web.app

**Review by tomlovesgithub — APPROVED** [review]

**Comment by KateMJAC** [comment]
@JeremykJAC @HalcyonJAC just checking in to see if you have seen my comment for this PR. 

UTG did have an issue, but it may not be related to this work and just a bug. 

Also there are now conflicts for this work so I couldn't merge.

**Comment by HalcyonJAC** [comment]
@KateMJAC ok I will sort. thanks for the heads-up!

**Comment by warrensearle** [comment]
Hi @HalcyonJAC and @KateMJAC I have fixed the merge conflicts so this is ready to be merged.
(one of my PRs is based off of this branch so am keen to get it merged 😄)

**Review by KateMJAC — COMMENTED** [review]
Happy for this to be merged, based on advice from Warren / Jeremy.

**Pull request merged**
